PROGRAM SUBDEM 

real A,B,C,SUM,SUMSQ 
A = 10.0
B = 20.0
C = 30.0

CALL CALC(A,B,C,SUM,SUMSQ)
CALL OUTPUT(SUM,SUMSQ)

END PROGRAM SUBDEM

SUBROUTINE CALC(A,B,C, SUM,SUMSQ)
 REAL, INTENT(INOUT):: A,B,C,SUM,SUMSQ
 SUM = A + B + C
 SUMSQ = SUM * SUM
END SUBROUTINE CALC

SUBROUTINE OUTPUT(SUM,SUMSQ)
  REAL,INTENT(IN) ::SUM, SUMSQ
  PRINT *,SUM
  PRINT *,SUMSQ
END SUBROUTINE OUTPUT
